# This is a basic workflow to help you get started with Actions

name: Shared Echo caller

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "echo"
  dotenv:
    uses: falti/dotenv-action//.github/actions/dotenv-action@master
    with:
      path: .github/workflows/.env.java
  echo:
    # The type of runner that the job will run on
    uses: shabahang/yup/.github/workflows/shared-echo.yml@master
    with:
      echo_text: ${{ steps.dotenv.outputs.is_java }}


  
