# This is a basic workflow to help you get started with Actions

name: Shared Echo caller

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "echo"
  loadwf:
    runs-on: ubuntu-latest
    steps:
      - name: dotenv
        #uses: falti/dotenv-action@v1
        uses: xom9ikk/dotenv@v2
        with:
          path: ./.github/workflows/.env.java
      - name: echo
        uses: shabahang/yup/.github/workflows/shared-echo.yml@master
        with:
          echo_text: ${{ env.is_java }}


  
